# Generated by Django 4.1.7 on 2024-03-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school_name', models.CharField(max_length=100)),
                ('school_email', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
