# Generated by Django 4.2.1 on 2024-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_form_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sp', 'Español'), ('ch_s', '中文简体'), ('ch_t', '中文繁體'), ('it', 'Italiano'), ('ar', 'عربي'), ('pu', 'ਪੰਜਾਬੀ'), ('fr', 'Français'), ('jp', '日本語'), ('kr', '한국인'), ('ger', 'Deutsch'), ('ru', 'Русский'), ('po', 'Português')], default='English', max_length=100),
        ),
    ]
