# Generated by Django 5.0.3 on 2024-03-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_form_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='translated_message',
            field=models.TextField(null=True),
        ),
    ]
